name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Test ${{ github.ref_name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64

    steps:
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install from repository
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache .
      - name: test using pytest
        run: |
          pytest -v --cov=src --cov-report=xml
